humor_posts = [
    "debugging at 3am when you realize it's a missing semicolon 💀",
    "me: this api will be simple. api: hold my 500 errors 😭",
    "wrote perfect code. lint: 42 violations ☠️",
    "deployed to prod. users: where's the dark mode? 💀",
    "git push --force. boss: who broke main? 😭",
    "npm install takes 45 minutes. cargo: done in 2s ☠️",
    "docker compose up. port already in use 💀",
    "wrote tests. they pass. prod fails anyway 😭",
    "microservices: 12 services for hello world ☠️",
    "legacy code: works but no one knows why 💀",
    "ai writes code. i debug it for hours 😭",
    "monday: refactor. friday: back to copy-paste ☠️",
    "kubernetes: pod evicted because oof 💀",
    "react state: useeffect hell 😭",
    "sql joins: 7 tables later lost in translation ☠️",
    "frontend dev touches backend. 500 everywhere 💀",
    "backend dev does ui. looks like geocities 😭",
    "agile: daily standup 45 mins ☠️",
    "waterfall: requirements change day 1 💀",
    "python: import this. zen achieved 😭",
    "rust borrow checker: my mortal enemy ☠️",
    "javascript this: who dis? 💀",
    "css specificity wars 😭",
    "commit message: 'fix typo' 500 lines later ☠️",
    "hotfix branch: becomes feature branch 💀",
    "code review: nitpick paradise 😭",
    "merge conflict: git gone wild ☠️",
    "env vars: prod has different names 💀",
    "secrets in repo: oops 😭",
    "cache invalidation: two hard problems ☠️",
    "naming things: the third 💀",
    "off by one error at midnight 😭",
    "stack overflow copy paste: works until prod ☠️",
    "refactor: breaks everything 💀",
    "tdd: test driven despair 😭",
    "ci/cd pipeline: red for days ☠️",
    "docker layers: 2gb hello world 💀",
    "aws bill: surprised pikachu 😭",
    "feature flag: forgot to toggle ☠️",
    "sql injection: params? what params 💀",
    "race condition: works on my machine 😭",
    "memory leak: gc pls ☠️",
    "regex: .*(.*).*(.*).* 💀",
    "api rate limit: too many requests 😭",
    "oauth dance: token expired ☠️",
    "webpack bundle: 10mb gzipped 💀",
    "sql no index: table scan party 😭",
    "cron job: overlaps itself ☠️",
    "log levels: debug in prod 💀",
    "password policy: tr0ub4dor&3 😭",
    "2fa: lost the code ☠️",
    "vpn drops mid deploy 💀",
    "ssh key expired 😭",
    "domain expired: site 404 ☠️",
    "backup restore: wrong version 💀",
    "migration down: oops prod 😭",
    "index rebuild: locks table ☠️",
    "shard key wrong: query hell 💀",
    "graphql n+1: classic 😭",
    "websocket reconnect: state gone ☠️",
    "service mesh: istio nightmare 💀",
    "helm chart: values.yaml war 😭",
    "terraform drift: reconcile pls ☠️",
    "secrets manager: rotated too early 💀",
    "observability: logs? metrics? traces? 😭",
    "slo alert: paging me at 2am ☠️",
    "postmortem: 'works on my machine' 💀",
    "blameless: yeah right 😭",
    "rto/rpo: theory vs reality ☠️",
    "chaos engineering: prod chaos 💀",
    "finops: cloud spend who? 😭",
    "value stream: mapping hell ☠️",
    "okrs: quarterly pivot 💀",
    "vibe coding: no tests 😭",
    "shipit: gates everywhere ☠️",
    "trunk based: feature flags galore 💀",
    "pair programming: one types one watches 😭",
    "mob programming: chaos ☠️",
    "code ownership: vacation nightmare 💀",
    "tech debt: sprint 47 😭",
    "spike: two weeks research ☠️",
    "poc: production ready 💀",
    "mvp: minimum viable pain 😭",
    "dogfood: internal beta hell ☠️",
    "beta users: edge cases 💀",
    "ga launch: 503 everywhere 😭",
    "black friday: scales? lol ☠️",
    "series a: refactor time 💀",
    "unicorn: burn rate 😭",
    "pivot: new buzzword ☠️",
    "acqui-hire: culture clash 💀",
    "layoffs: friday email 😭",
    "h1b visa: lottery ☠️",
    "remote work: zoom fatigue 💀",
    "return to office: commute hell 😭",
    "async comms: slack flood ☠️",
    "townhall: ceo vision 💀",
    "all hands: metrics down 😭",
    "perks: free snacks gone ☠️",
    "401k match: paused 💀",
    "rsus: underwater 😭",
    "promo: next year ☠️",
    "raise: cost of living 💀",
    "burnout: grindset ☠️ wait no 😭",
    "fourth coffee: still bugs 💀",
    "rubber duck: explains better ☠️",
    "stackoverflow ban: duplicate 😭",
    "chatgpt code: subtle bugs 💀",
    "copilot: accepts all ☠️",
    "llm hallucinate: api docs wrong 😭",
    "prompt eng: novel length 💀",
    "rags: chunking wars ☠️",
    "embeddings: vector db bill 😭",
    "agents: infinite loop 💀",
    "tool calling: wrong args ☠️",
    "fine tune: data poison 😭",
    "eval set: overfitting 💀",
    "prod ai: drift city ☠️",
    "guardrails: bypassed 😭",
    "a/b test: p-hack 💀",
    "metrics: vanity ☠️",
    "retention: churn funnel 😭",
    "l tv c: lifetime value lol 💀",
    "mrr: stripe fees ☠️",
    "churn: forgot to bill 😭",
    "upsell: feature gate 💀",
    "saas fatigue: 50 tabs ☠️",
    "nocode: limits hit 😭",
    "bubble: slow af 💀",
    "webflow: css overrides ☠️",
    "zapier: task limit 😭",
    "airtable: row limit 💀",
    "notion: api rate ☠️",
    "make: complex flows 😭",
    "indie hacker: weekend mvp 💀",
    "product hunt: 50 upvotes ☠️",
    "hn: flamewar 😭",
    "reddit: karma negative 💀",
    "twitter algo: shadowban ☠️",
    "linkedin: humble brag 😭",
    "tiktok dev: algorithm hack 💀",
    "youtube tutorial: outdated ☠️",
    "udemy course: 0.99 sale 😭",
    "bootcamp: six figures debt 💀",
    "cs degree: irrelevant ☠️",
    "self taught: imposter 💭 😭",
    "open source: maintainer burnout 💀",
    "stars: buy github stars ☠️",
    "contributors: 1 😭",
    "issue triage: stale bot 💀",
    "pr review: waiting 6mo ☠️",
    "dependabot: security hell 😭",
    "node 20 eol: upgrade pls 💀",
    "php 8: still legacy 😭",
    "cobol: y2k38 💀",
    "foxpro: eternal ☠️",
    "mainframe: green screen 😭",
    "blockchain: nft winter 💀",
    "web3: gas fees ☠️",
    "solana: outage again 😭",
    "eth merge: pos promises 💀",
    "defi: rug pull ☠️",
    "ai winter: hype cycle 😭",
    "metaverse: empty worlds 💀",
    "vr: motion sick ☠️",
    "ar: filters only 😭",
    "iot: security nightmare 💀",
    "5g: same speeds ☠️",
    "quantum: 10 years away 😭",
    "fusion: always 30 years 💀",
    "agi: this year lol ☠️",
    "singularity: upload consciousness 😭",
    "mars colony: elon time 💀"
]

# Add more to max ~300
humor_posts += [
    "pairing with junior: explains basics 💀",
    "senior dev: rubber duck level 😭",
    "cto codes: hello world ☠️",
    "product manager: as a user 💀",
    "designer: pixel push figma 😭",
    "qa: edge cases master ☠️",
    "devops: infra as code 💀",
    "sales: feature request daily 😭",
    "marketing: seo keywords ☠️",
    "hr: unlimited pto myth 💀",
    "friday deploy: never 💀",
    "weekend oncall: bingo 😭",
    "pager duty: escalations ☠️",
    "incident cmd: war room 💀",
    "rollback: db migration no 😭",
    "hotfix prod: fingers crossed ☠️",
    "canary deploy: 1% who? 💀",
    "blue green: swap fail 😭",
    "git bisect: cursed commit ☠️",
    "flame graph: cpu fire 💀",
    "strace: syscall hell 😭",
    "gdb: segfault party ☠️",
    "valgrind: leaks everywhere 💀",
    "perf: flamegraph zoom 😭",
    "blackbox: mystery func ☠️",
    "whitebox: internals nightmare 💀",
    "end to end: flaky af 😭",
    "unit test: mocks galore ☠️",
    "integration: db setup 💀",
    "snapshot: golden file drift 😭",
    "cypress: slow network ☠️",
    "playwright: browser farm 💀",
    "selenium: webdriver pain 😭",
    "pytest: fixture wars ☠️",
    "jest: timeout hell 💀",
    "vitest: vite speed 😭",
    "bun test: fast but new ☠️",
    "go test: table driven 💀",
    "rspec: matchers deep 😭",
    "cucumber: gherkin glue ☠️",
    "behave: python bdd 💀",
    "jest snapshot: regenerate 😭",
    "coverage 100%: lies ☠️",
    "mutation testing: kill mutants 💀",
    "property based: quickcheck 😭",
    "fuzzing: crash repro ☠️",
    "chaos monkey: netflix style 💀",
    "gremlin: graph attacks 😭",
    "litmus: k8s chaos ☠️",
    "duplicate code: sonar weep 💀",
    "cyclomatic: god func 😭",
    "solid principles: violated ☠️",
    "dry: wets everywhere 💀",
    "kiss: overengineered 😭",
    "yagni: built anyway ☠️",
    "big design up front: waterfall 💀",
    "evolutionary: spike first 😭",
    "hexagonal: ports adapters ☠️",
    "cqrs: read write split 💀",
    "event sourcing: append only 😭",
    "saga pattern: distributed tx ☠️",
    "actor model: message passing 💀",
    "fp pure: side effects none 😭",
    "oop inheritance: diamond death ☠️",
    "composition: has a wins 💀",
    "prototypal: js quirks 😭",
    "structural typing: go unions ☠️",
    "nominal: rust enums 💀",
    "sum types: either or 😭",
    "adt: algebraic data ☠️",
    "monad: burrito hell 💀",
    "functor: map flatmap 😭",
    "applicative: <*> pure ☠️",
    "comonad: cobind extend 💀",
    "category theory: prod too far 😭"
]

print(f"Loaded {len(humor_posts)} jokes")