humor_posts = [
    "why programmers hate nature too many bugs",
    "api always promise ice cream",
    "git commit past tense of git stahp",
    "docker boxes for noobs",
    "k8s kubernetees too long to spell",
    "javascript hoisting party in the backyard",
    "python indentation error whitespace drama",
    "rust borrow checker loan shark",
    "go goroutines leak like teenagers",
    "java garbage collection pause button",
    "c pointer dereference wild west",
    "php superglobal $_get post party",
    "ruby on rails convention over config regret",
    "scala category theory overkill",
    "haskell monad burrito wrapper",
    "clojure parenthesis hell lisp",
    "elixir actor model otp supervision",
    "erlang let it crash philosophy",
    "perl regex golf champion",
    "cobol punch card nostalgia",
    "fortran do loop index off by one",
    "assembly mov ax bx dad joke",
    "sql select dad from jokes where pun = true",
    "nosql document no schema freedom",
    "graphql query mutation subscription trinity",
    "rest http verb confusion",
    "soap xml envelope heavy",
    "grpc protobuf compact",
    "websocket full duplex chatty",
    "mqtt pub sub lightweight",
    "amqp rabbit hole",
    "kafka stream process exactly once",
    "pulsar partitioned topic",
    "nats lightweight msg",
    "zeromq brokerless",
    "redis list pop lpush rpop",
    "memcached slab alloc",
    "etcd kv watch lease",
    "consul service mesh",
    "zookeeper coord lock",
    "chubby google lock",
    "paxos consensus algorithm",
    "raft leader election",
    "zab zab zab zookeeper atomic broadcast",
    "viewstamped replication",
    "pbft byzantine fault",
    "hotstuff lin chuan",
    "tendermint cometbft",
    "libp2p peer discovery",
    "ipfs content address",
    "orbitdb ipfs db",
    "filecoin storage market",
    "arweave blockweave",
    "sia host contract",
    "storj satellite",
    "crust ipfs",
    "bluzelle swarm db",
    "akash marketplace",
    "golem compute",
    "render network",
    "io net storage",
    "akash dep provider",
    "dfinity canister",
    "internet computer",
    "substrate runtime",
    "polkadot relay chain",
    "kusama canary",
    "moonbeam evm parachain",
    "astar collab",
    "acala karura",
    "phala tdee",
    "centrifuge tinlake",
    "interlay ibtc",
    "basilisk liquidity",
    "hydradx omni pool",
    "statemint assets",
    "nodle network",
    "peaq iot",
    "subspace proof stake",
    "frequency radio",
    "energy web",
    "ocean market",
    "singularity net",
    "fetch ai",
    "ocean protocol",
    "singularitydao",
    "agix fetch",
    "asi synthetic",
    "solidity pragma",
    "vyper v lang",
    "fe language",
    "ink pallet",
    "solang llvm",
    "move sui aptos",
    "cadence flow",
    "clarity stacks",
    "reach react",
    "scallop",
    "pragma ink",
    "cargo contract",
    "solc compiler",
    "hardhat ethers",
    "foundry forge",
    "anvil cast",
    "remix ide",
    "tenderly dashboard",
    "thirdweb sdk",
    "alchemy sdk",
    "infura ipfs",
    "mor alis web3",
    "quicknode endpoints",
    "pocket network",
    "lavanet rpc",
    "dcent rpc",
    "ankr premium",
    "getblock dedicated",
    "ionet relay",
    "figment staking",
    "stakin node",
    "allnodes managed",
    "node real",
    "inf stones",
    "p2p validator",
    "everstake",
    "chorus one",
    "stakin labs",
    "figment staking",
    "stader labs",
    "parafi cap",
    "lido dao",
    "rocket pool",
    "stakewise",
    "an kr stkr",
    "chorus stkr",
    "stader stkr",
    "parafi stkr",
    "lido steth",
    "cbeth coinbase",
    "rpl rocket",
    "stakewise os",
    "flexible staking",
    "liquid staking",
    "restaking eigen",
    "symbiotic shared sec",
    "renzo ezeth",
    "kelp rsi eth",
    "puffer uni v2",
    "blast gold",
    "alt layer restake",
    "mellow protocol",
    "kyros restake",
    "steakhouse rsi",
    "morpho rsi",
    "pendle rsi",
    "ether fi",
    "wefi we eth",
    "swell lrt",
    "frxeth frax",
    "sfrxeth",
    "cbeth coinbase",
    "ibit blackrock",
    "fbtc fidelity",
    "hith trust",
    "peth grvt",
    "rs eth renzo",
    "ez eth renzo",
    "we eth we",
    "sw eth swell",
    "rsw eth",
    "frx eth frax",
    "sfrx eth",
    "cb eth coinbase",
    "ib it blackrock",
    "f btc fidelity",
    "hi th trust",
    "p eth grvt",
    "rsi eth steak",
    "morph rsi",
    "pendle rsi",
    "ether.fi eeth",
    "wefi weeth",
    "swell lrt",
    "altlayer restake",
    "mellow rsi",
    "kyros rsi",
    "steak rsi",
    "symb shared",
    "eigen restake",
    "irys arweave",
    "bundlr sol",
    "helius rpc",
    "quicknode sol",
    "genesysgo rpc",
    "triton rpc",
    "lavanet sol",
    "dcent sol",
    "ankr sol",
    "getblock sol",
    "ionet sol",
    "figment sol",
    "stakin sol",
    "allnodes sol",
    "node real sol",
    "infstones sol",
    "p2p sol",
    "everstake sol",
    "chorus sol",
    "stakin labs sol",
    "figment sol stake",
    "stader sol",
    "parafi sol",
    "lido sol",
    "jito sol stake",
    "blaze stake",
    "sanctum lsd",
    "marginfi lend",
    "kam ino lend",
    "solend lend",
    "tulip lend",
    "port finance",
    "save finance",
    "larix lend",
    "maple lend",
    "zulu lend",
    "flux finance",
    "francium",
    "tulip protocol",
    "solend",
    "kam ino",
    "marginfi",
    "portfi",
    "drift protocol",
    "mango markets",
    "zeta markets",
    "gmx v2",
    "perpetual protocol",
    "dydx v4",
    "gains network",
    "synthetix v3",
    "lyra options",
    "opyn options",
    "hegic options",
    "premia options",
    "deri protocol",
    "storm trade",
    "thales market",
    "polymarket pred",
    "augur v2",
    "gnosis conditional",
    "uma optimistic",
    "tellor oracle",
    "chainlink ccip",
    "pyth network",
    "redstone oracle",
    "supra oracles",
    "api3 airnode",
    "band protocol",
    "dovr oracles",
    "dia data",
    "tellor tributes",
    "witnet decentralized",
    "nest protocol",
    "pancake oracles",
    "synthetix chainlink",
    "aave chainlink",
    "compound chainlink",
    "maker mcd",
    "yearn ycrv",
    "convex crv",
    "vis a lizer",
    "stake dao",
    "alchemix self repay",
    "reflexer dai",
    "liquity lusd",
    "rai reflexer",
    "crv usd",
    "iron bank",
    "dydx v3",
    "aave v3",
    "compound v3",
    "uniswap v4",
    "curve v2",
    "balancer v3",
    "clipper amm",
    "bancor v3",
    "kyber dmm",
    "1inch fusion",
    "cow protocol",
    "0x v4",
    "matcha api",
    "jupiter aggregator",
    "1inch api",
    "open ocean",
    "slingshot",
    "paraswap",
    "0x api aggregator",
    "dex screener",
    "dex tools",
    "dex guru",
    "poocoin chart",
    "dexscreener",
    "birdeye sol",
    "dexscreener sol",
    "jupiter terminal",
    "raydium swap",
    "orca swap",
    "pump fun",
    "moonshot",
    "sol trading bot",
    "trojan bot",
    "bonk bot",
    "sol sniper",
    "maestro bot",
    "sol copy trade",
    "banana gun",
    "photon sol",
    "sol blaze",
    "trojan on sol",
    "bonk bot sol",
    "unibot eth",
    "maestro sniper",
    "mizar api",
    "shogun api",
    "sol trading api",
    "jupiter api v6",
    "raydium sdk",
    "orca sdk",
    "solana program lib",
    "anchor framework",
    "solana cli",
    "solana test validator",
    "solana localnet",
    "anchor test",
    "mochisol test",
    "solana program test",
    "solana logs",
    "solana balance",
    "solana airdrop",
    "solana keygen",
    "solana config set",
    "solana program deploy",
    "solana program show",
    "solana account",
    "solana sig confirm",
    "solana rpc api",
    "solana json rpc",
    "solana rpc node",
    "helius rpc",
    "quicknode rpc",
    "genesysgo rpc",
    "triton one",
    "syndica rpc",
    "lavanet rpc",
    "dcent rpc",
    "ankr rpc",
    "getblock rpc",
    "mainnet beta",
    "devnet",
    "testnet",
    "localnet",
    "solana validator",
    "stake account",
    "vote account",
    "solana stake",
    "solana vote",
    "jito stake pool",
    "blaze stake",
    "sanctum stake",
    "marginfi stake",
    "jito sol staker",
    "backpack wallet",
    "phantom wallet",
    "solflare wallet",
    "solfare web",
    "backpack app",
    "solflare ledger",
    "phantom mobile",
    "solflare mobile",
    "backpack swap",
    "jupiter mobile",
    "raydium mobile",
    "orca mobile",
    "pump fun mobile",
    "solana mobile stack",
    "saga phone",
    "seeker phone",
    "solana mobile sdk",
    "solana pay",
    "solana mobile aggregator",
    "squads multisig",
    "squads protocol",
    "daemon multisig",
    "spl governance",
    "realms solana",
    "tulip protocol",
    "solend protocol",
    "marginfi protocol",
    "kam ino protocol",
    "port finance",
    "drift protocol",
    "mango v4",
    "zeta protocol",
    "gmx solana",
    "perpetual protocol sol",
    "dydx solana",
    "gains network sol",
    "synthetix solana",
    "lyra solana",
    "opyn solana",
    "hegic solana",
    "premia blue",
    "deri protocol sol",
    "storm trade sol",
    "thales market sol",
    "polymarket sol",
    "augur solana",
    "gnosis conditional sol",
    "uma solana",
    "tellor solana",
    "chainlink solana",
    "pyth solana",
    "redstone solana",
    "supra solana",
    "api3 solana",
    "band protocol sol",
    "dia solana",
    "switchboard solana",
    "uploading oracle",
    "solend oracle",
    "mango oracle",
    "drift pyth",
    "jupiter oracle",
    "pyth crosschain",
    "switchboard v2",
    "pyth express relay",
    "pyth wormhole",
    "solana wormhole",
    "allbridge solana",
    "debridge solana",
    "layerzero solana",
    "axelar solana",
    "ccip solana",
    "socket solana",
    "synapse solana",
    "hop solana",
    "across solana",
    "stargate solana",
    "multichain solana",
    "anyswap solana",
    "connext solana",
    "li fi solana",
    "rango solana",
    "jumper solana",
    "1inch solana",
    "0x solana",
    "cow solana",
    "dexlab solana",
    "serum dex",
    "open book",
    "phoenix v1",
    "goblin trader",
    "open orders",
    "ldex",
    "lifinity",
    "invariant",
    "sabre",
    "step finance",
    "accele raytor",
    "saros",
    "maverick",
    "raydium cp mm",
    "orca whirlpools",
    "pump fun bonding",
    "jupiter perps",
    "drif t v2",
    "mango markets v4",
    "zeta perpetuals",
    "gmx v2 arbitrum",
    "gmx solana",
    "perps dex",
    "dydx v4 cosmo",
    "gains gns",
    "synthetix perps",
    "lyra avs",
    "opyn squeeth",
    "hegic eth",
    "premia finance",
    "stormgain",
    "thales limited",
    "polymarket u ma",
    "augur turbo",
    "gnosis gnosis chain",
    "uma t t",
    "tellor jr",
    "dia oracle",
    "switchboard 1.9",
    "pyth e vm",
    "redstone evm",
    "supra evm",
    "api3 beefy",
    "band chain",
    "dia evm",
    "uploading v2",
    "solend v2",
    "mango v5",
    "drift v2",
    "jupiter v7",
    "backpack exchange",
    "phantom perps",
    "solflare perps",
    "jupiter perps",
    "orca perps",
    "raydium perps",
    "pump perps",
    "solana fm",
    "solscan explorer",
    "solana explorer",
    "explorer solana",
    "solana beach",
    "solanafloor nft",
    "tensor nft",
    "magic eden",
    "opensea solana",
    "hyperspace nft",
    "solanart",
    "exchange artifacts",
    "solanax",
    "serum dex v3",
    "openbook v2",
    "phoenix trader",
    "goblin markets",
    "ldex v2",
    "lifinity v2",
    "invariant v2",
    "sabre v2",
    "step v2",
    "accele r v2",
    "saros v2",
    "maverick v2",
    "raydium ammv4",
    "orca v2",
    "pump bonding v2",
    "jupiter lfg",
    "backpack lfg",
    "phantom lfg",
    "solflare lfg",
    "jupiter mobile v2",
    "orca mobile v2",
    "raydium mobile v2",
    "pump mobile",
    "solana mobile 2.0",
    "saga 2",
    "seeker solana phone",
    "solana saga chapter 2",
    "solana mobile sdk 2",
    "solana pay qr",
    "solana pay nfc",
    "squads v2",
    "squads protocol v2",
    "daemon v2",
    "spl governance v2",
    "realms v2",
    "tulip v2",
    "solend v2",
    "marginfi v2",
    "kamino v2",
    "port v2",
    "drift v3",
    "mango v5",
    "zeta v2",
    "gmx sol v2",
    "perpetuals v2",
    "dydx sol v2",
    "gains v2",
    "synthetix sol v2",
    "lyra v2",
    "opyn v2",
    "hegic v2",
    "premia v2",
    "deri v2",
    "storm v2",
    "thales v2",
    "polymarket v2",
    "augur v3",
    "gnosis v2",
    "uma v2",
    "tellor v2",
    "chainlink v2",
    "pyth v2",
    "redstone v2",
    "supra v2",
    "api3 v2",
    "band v2",
    "dia v2",
    "switchboard v2",
    "uploading v2",
    "solend oracle v2",
    "mango oracle v2",
    "drift pyth v2",
    "jupiter oracle v2",
    "pyth cross v2",
    "switchboard v3",
    "pyth express v2",
    "pyth wormhole v2",
    "solana wormhole v2",
    "allbridge v2",
    "debridge v2",
    "layerzero v2",
    "axelar v2",
    "ccip v2",
    "socket v2",
    "synapse v2",
    "hop v2",
    "across v4",
    "stargate v2",
    "multichain v2",
    "anyswap v2",
    "connext v2",
    "li fi v2",
    "rango v2",
    "jumper v2",
    "1inch v2",
    "0x v5",
    "cow v2",
    "dexlab v2",
    "serum v4",
    "open book v2",
    "phoenix v2",
    "goblin v2",
    "ldex v3",
    "lifinity v3",
    "invariant v3",
    "sabre v3",
    "step v3",
    "accele r v3",
    "saros v3",
    "maverick v3",
    "raydium ammv5",
    "orca v3",
    "pump bonding v3",
    "jupiter v8",
    "backpack v2",
    "phantom v2",
    "solflare v2",
    "jupiter mobile v3",
    "orca mobile v3",
    "raydium mobile v3",
    "pump mobile v2",
    "solana mobile 3.0",
    "saga 3",
    "seeker v2",
    "solana saga chapter 3",
    "solana mobile sdk 3",
    "solana pay v2",
    "solana pay nfc v2",
    "squads v3",
    "squads protocol v3",
    "daemon v3",
    "spl governance v3",
    "realms v3",
    "tulip v3",
    "solend v3",
    "marginfi v3",
    "kamino v3",
    "port v3",
    "drift v4",
    "mango v6",
    "zeta v3",
    "gmx v3",
    "perpetuals v3",
    "dydx v5",
    "gains v3",
    "synthetix v4",
    "lyra v3",
    "opyn v3",
    "hegic v3",
    "premia v3",
    "deri v3",
    "storm v3