humor_posts = [
    "sv saas metrics mrr churn vanity dashboard",
    "ny proptech lease renewal code refactor",
    "austin edtech zoom fatigue student edition",
    "to healthtech waitlist longer than nhs",
    "fe motion design lottie file size bomb",
    "ui accessibility screen reader nightmares",
    "ai fine tune data labeler sweatshop",
    "dev rel conference swag unboxing ritual",
    "sv crypto winter nft profile pic regret",
    "ny adtech cookie deprecation panic",
    "austin cleantech solar panel iot fleet",
    "toronto quantum computing hype cycle repeat",
    "backendless no code backend dreams shatter",
    "jamstack static site dynamic content hack",
    "pwa service worker cache bust fail",
    "sv growth hack a b test p value fudge",
    "ny compliance officer startup killer",
    "austin podcast guest devrel tour",
    "to ai safety alignment paper reading club",
    "tailwind dark mode media query toggle",
    "framer site deploy vercel preview branch",
    "webflow cms dynamic content limit",
    "sv angel investor coffee chat pipeline",
    "ny family office lp allocation drama",
    "austin accelerator equity take dilution",
    "toronto government grant paperwork marathon",
    "zustand persist middleware localstorage quota",
    "jotai devtools chrome extension debug",
    "recoil snapshot testing golden file",
    "sv runway extension bridge round desperation",
    "ny down round valuation reset pain",
    "austin solo founder cofounder hunt",
    "to immigrant founder visa extension stress",
    "docker multi stage build layer cache miss",
    "k8s horizontal pod autoscaler cpu throttle",
    "argo cd gitops sync drift detect",
    "sv talent war senior eng signing bonus",
    "ny finance bro quant trading strat backtest",
    "austin music fest dev afterparty network",
    "toronto film fest tech sponsor badge flex",
    "next auth session strategy jwt vs db",
    "clerk user management magic link spam",
    "supabase auth custom token claim",
    "sv hype cycle trough of disillusionment",
    "ny bear market short squeeze meme",
    "austin longhorn stadium wifi overload",
    "to leafs playoff ticket scalper bots",
    "vite plugin ssr manifest hydration mismatch",
    "eslint prettier conflict format war",
    "husky pre commit lint staged git hook",
    "sv unicorn graveyard post money valuation",
    "ny ipo roadshow pitch book polish",
    "austin capital one tech campus commute",
    "toronto rogers centre drone light show",
    "prisma accelerate connection pool exhaust",
    "planetscale boost query optimize index hint",
    "cockroach db distributed sql cockroach jokes",
    "sv deck pdf vs figma interactive prototype",
    "ny cap table excel model scenario analysis",
    "austin ut austin cs dropout rate",
    "to uoft cs waitlist lottery",
    "remix vite integration loader suspense",
    "hono middleware cors helmet rate limit",
    "t3 stack next trpc tailwind typescript",
    "sv founder mode solo gp bet",
    "ny prop a prop c funding ballot",
    "austin electric scooter sidewalk ban",
    "toronto streetcar delay ttc punchline",
    "shadcn button variant slot api abuse",
    "radix dialog portal overflow hidden",
    "headless dropdown keyboard nav aria",
    # ~300 punchy no-emoji hub jokes...
    "turbopack nextjs swc compile speed"
]

print(f"Loaded {len(humor_posts)} super punchy hub jokes no emojis")